services:
  jekyll:
    build: .
    container_name: jekyll_server
    volumes:
      - .:/srv/jekyll
      - bundle_data:/usr/local/bundle
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0
    restart: unless-stopped

volumes:
  bundle_data:
